# Generated by Django 6.1.1 on 2026-09-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('A1+', 'A1+'), ('A1-', 'A1-'), ('A2+', 'A2+'), ('A2-', 'A2-'), ('A1B+', 'A1B+'), ('A1B-', 'A1B-'), ('A2B+', 'A2B+'), ('A2B-', 'A2B-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Oh+', 'Oh+ (Bombay)'), ('Oh-', 'Oh- (Bombay)')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('A1+', 'A1+'), ('A1-', 'A1-'), ('A2+', 'A2+'), ('A2-', 'A2-'), ('A1B+', 'A1B+'), ('A1B-', 'A1B-'), ('A2B+', 'A2B+'), ('A2B-', 'A2B-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Oh+', 'Oh+ (Bombay)'), ('Oh-', 'Oh- (Bombay)')], max_length=5),
        ),
    ]
